name: T. Anil Sengül, A participant of PowerCoders
markdown: kramdown
permalink: /menu/blog/:year/:month/:day/:title

theme: jekyll-theme-modernist
#gems:
#  - jekyll-paginate

#paginate_path: "/blog/page:num/"
#paginate: 100
